#!/usr/bin/env bash

if [[ "$#" != "5" ]]; then {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}
fi
scp -o "StictHostKeyChecking yes" -i "$4" "$1" "$2"@"$3":~/
