#!/usr/bin/env bash 
# install and configure nginx 
apt-get -y install ufw 
apt-get -y install nginx 
ufw allow "Nginx http"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
if [ "$(pgrep -c nginx)" -le 0 ]; then
    nginx -s start
else
    nginx -s reload
fi
exit 0
