#!/usr/bin/env bash
# configures an nginx server 

apt-get update 
apt-get -y nginx 
if  ufw app list | grep -c "Nginx HTTP" 
then
    ufw allow "Nginx HTTP"
else
    apt-get -y install ufw
    ufw allow "Nginx HTTP"
fi

chown "$USER":"$USER" "/var/www/html/index.nginx-debian.html"
echo "Hello World" > "/var/www/html/index.nginx-debian.html"
service start nginx;
