#!/usr/bin/env bash 
# install and configure nginx
REPL="\(\s\)server_name _;"
REPL_WITH="\1server_name _; \\n   rewrite ^\/.+?_me https:\/\/www.youtube.com\/watch?v=QH2-TGULwu4" 
TMP_FILE="\tmp\default_tmp"
OUT_CONF="/etc/nginx/sites-available/default"
apt-get install ufw 
apt-get install nginx 
ufw allow "Nginx http"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# file manipulation
sed "s/$REPL/$REPL_WITH/1" "$OUT_CONF" >> "$TMP_FILE"
cat "$TMP_FILE" >> $OUT_CONF  
service nginx restart
exit 0 
