#!/usr/bin/env bash 
# install and configure nginx
REPL="\(\s\)server_name _;"
REPL_WITH="\1server_name _; \\n\1rewrite ^\/.+?_me https:\/\/www.youtube.com\/watch?v=QH2-TGULwu4;" 
TMP_FILE="/tmp/default_tmp"
OUT_CONF="/etc/nginx/sites-available/default"
apt-get install ufw 
apt-get install nginx 
ufw allow "Nginx http"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# idempotent 
if [  "$(grep -c "^\srewrite.*?;$")" -le 0 ]; then 
    {
        # file manipulation
        sed "s/$REPL/$REPL_WITH/1" $OUT_CONF >> $TMP_FILE
        cat $TMP_FILE >> $OUT_CONF
        rm $OUT_CONF 
    }
fi

if (nginx -t); then { exit 1; }; fi
if [ "$(pgrep -c nginx)" -le 0 ]; then 
    service nginx start 
else 
    service nginx restart
fi
    exit 0 
