#!/usr/bin/env bash 
# install and configure nginx
REPL="\s\?server_name \(.*\);"
REPL_WITH="\tserver_name \1; \\n\trewrite ^\/.+?_me https:\/\/www.youtube.com\/watch?v=QH2-TGULwu4;" 
TMP_FILE="/tmp/default_tmp"
OUT_CONF="/etc/nginx/sites-available/default"
ERR_PG="/var/www/html/custom_404.html"
APP_TXT="\terror_page 404 /custom_404.html;
\tlocation = /custom_404.html {
\t\troot /var/www/html;
\t\tinternal;
}"
apt-get install ufw 
apt-get install nginx 
ufw allow "Nginx http"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# idempotent 
if ! ( grep -c 'rewrite' "$OUT_CONF" ); then 
    {
        # file manipulation
        sed -e "/^[^#]/ s/$REPL/$REPL_WITH/1" $OUT_CONF > $TMP_FILE
        cat $TMP_FILE > $OUT_CONF
        rm $TMP_FILE 
    }
fi
if ! ( grep -c "Ceci" $ERR_PG); then
    echo "Ceci n'est pas une page" | sudo tee $ERR_PG 
fi
if ! (grep -c 'custom_404.html' $OUT_CONF ); then
    {
        sed -e "/listen\[::\]:80*;/ a$APP_TXT" $OUT_CONF > $TMP_FILE 
        cat $TMP_FILE
        rm $TMP_FILE
    }
fi
if ! (nginx -t); then { exit 1; }; fi
if  ( pgrep -c nginx ); then 
    service nginx start 
else 
    service nginx restart
fi
exit 0  
