#!/usr/bin/env bash 
REPL="\sserver_name \(.*\);"
REPL_WITH="\tserver_name \1; \\n\trewrite ^\/.+?_me https:\/\/www.youtube.com\/watch?v=QH2-TGULwu4;" 
sed -e "/^[^#]/ s/$REPL/$REPL_WITH/1" test_string | uniq -u 
