#!/usr/bin/env bash
# sets up a new 404 error page
apt-get update
apt-get install -y nginx 
echo "Hello World!" > index.html
HOSTN=$(hostname)
mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
mv 404.html /var/www/html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo tee /etc/nginx/sites-available/default > /dev/null << EOT
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location = /404.html{
        internal;
    }

    add_header X-Served-By $HOSTN;
}
EOT
if ! (nginx -t); then { exit 1; }; fi
if ! ( pgrep -c nginx ); then 
    service nginx start 
else 
    service nginx restart
fi
exit 0    
