#!/bin/bash

CONFIG_DIR="/etc/haproxy/"
DEFAULT_FILE="/etc/default/haproxy"

# Update package repositories
apt update
apt-get install --no-install-recommends -y software-properties-common

# Add HAProxy repository and install HAProxy
add-apt-repository -y ppa:vbernat/haproxy-2.7
apt-get install haproxy=2.7.*

# Enable HAProxy service
if ! grep -q "ENABLED" "$DEFAULT_FILE"; then
    echo "ENABLED=1" >> "$DEFAULT_FILE"
else
    sed -i 's/ENABLED=.*/ENABLED=1/' "$DEFAULT_FILE"
fi

# Backup and modify HAProxy configuration file
cp "$CONFIG_DIR/haproxy.cfg" "$CONFIG_DIR/haproxy.cfg.orig"
sed -i '/\tmode\s/s/tcp/http/1' "$CONFIG_DIR/haproxy.cfg"
sed -i '/\toption\s/s/tcplog/httplog/1' "$CONFIG_DIR/haproxy.cfg"

# Append frontend and backend configurations to the HAProxy configuration file
if ! grep -q "frontend" "$CONFIG_DIR/haproxy.cfg"; then
    cat <<EOT >> "$CONFIG_DIR/haproxy.cfg"
frontend www
    bind *:80 
    default_backend web01_02_backend

backend web01_02_backend
    balance roundrobin
    mode http
    server 152562-web-01 54.160.79.245:80 check 
    server 152562-web-02 18.234.129.129:80 check 
EOT
fi

# Start or restart HAProxy service
if ! pgrep -x "haproxy" > /dev/null; then
    service haproxy start
else
    service haproxy restart
fi
