#!/bin/bash 
# configure HAPROXY
CONFIG_DIR="/etc/haproxy/"
DEFAULT_FILE="/etc/default/haproxy"
apt update 
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.7
apt-get install haproxy=2.7.\*
if ! (grep -c "ENABLED"); then 
    tee -a "$DEFAULT_FILE" > /dev/null << EOT
ENABLED=1 
EOT
else 
    sed -i "ENABLED=s/./1/1"
fi
cp "$CONFIG_DIR/haproxy.cfg" "$CONFIG_DIR/haproxy.cfg.orig" 
sed -i "/\tmode\s/s/tcp/http/1" "$CONFIG_DIR/haproxy.cfg"
sed -i "/\toption\s/s/tcplog/httplog/1" "$CONFIG_DIR/haproxy.cfg"
if ! (grep -c frontend "$CONFIG_DIR/haproxy.cfg"); then
tee -a "$CONFIG_DIR/haproxy.cfg" > /dev/null << EOT
frontend www
    bind 34.203.77.97:80 
    default_backend web01_02_backend
backend web01_02_backend
    balance roundrobin
    mode http
    server 152562-web-01 54.160.79.245:80 check 
    server 152562-web-02 18.234.129.129:80 check 
EOT
fi
if ! (pgrep -c haproxy); then
    { service haproxy start; }
else
    { service haproxy restart; }
fi
