#!/usr/bin/env bash 
# create a backup of the database 

if [[ $# -eq 2 ]]; then 
    mysqldump -u root --all-databases -p"$1" --result-file backup.sql
else 
    mysqldump -u root --all-databases --result-file backup.sql
fi
archive_name="$(date +'%d-%m-%Y').tar.gz"
gzip -c backup.sql "$archive_name"
